-- =====================================================
-- SQL DATA ANALYSIS PROJECT
-- Database: ecommerce_db
-- Table: orders
-- =====================================================

-- =====================================================
-- Query 1: Select the Database
-- Purpose: Set ecommerce_db as the active database.
-- =====================================================

USE ecommerce_db;

-- =====================================================
-- Query 2: Count Total Number of Orders
-- Purpose: Find the total number of records in the orders table.
-- =====================================================

SELECT COUNT(*) AS Total_Orders
FROM orders;

-- =====================================================
-- Query 3: Rename OrderID Column
-- Purpose: Remove unwanted UTF-8 BOM characters from the column name.
-- (Run only once if needed.)
-- =====================================================

ALTER TABLE orders
CHANGE COLUMN `ï»¿OrderID` OrderID TEXT;

-- =====================================================
-- Query 4: Display Order ID, Product and Quantity
-- Purpose: View important columns from the dataset.
-- =====================================================

SELECT OrderID, Product, Quantity
FROM orders;

-- =====================================================
-- Query 5: Display Unique Products
-- Purpose: List all unique product names.
-- =====================================================

SELECT DISTINCT Product
FROM orders;

-- =====================================================
-- Query 6: Find All Phone Orders
-- Purpose: Display orders where the product is Phone.
-- =====================================================

SELECT *
FROM orders
WHERE Product = 'Phone';

-- =====================================================
-- Query 7: Sort Orders by Total Price
-- Purpose: Display highest-value orders first.
-- =====================================================

SELECT OrderID, Product, TotalPrice
FROM orders
ORDER BY TotalPrice DESC;

-- =====================================================
-- Query 8: Calculate Total Sales by Product
-- Purpose: Find revenue generated by each product.
-- =====================================================

SELECT Product,
       SUM(TotalPrice) AS Total_Sales
FROM orders
GROUP BY Product;

-- =====================================================
-- Query 9: Calculate Total Revenue
-- Purpose: Find overall sales revenue.
-- =====================================================

SELECT SUM(TotalPrice) AS Total_Revenue
FROM orders;

-- =====================================================
-- Query 10: Calculate Average Order Value
-- Purpose: Find the average value of an order.
-- =====================================================

SELECT AVG(TotalPrice) AS Average_Order_Value
FROM orders;

-- =====================================================
-- Query 11: Find Highest Order Value
-- Purpose: Display the maximum order amount.
-- =====================================================

SELECT MAX(TotalPrice) AS Highest_Order
FROM orders;

-- =====================================================
-- Query 12: Find Lowest Order Value
-- Purpose: Display the minimum order amount.
-- =====================================================

SELECT MIN(TotalPrice) AS Lowest_Order
FROM orders;

-- =====================================================
-- Query 13: Display Top 10 Highest Value Orders
-- Purpose: Show the highest-priced orders.
-- =====================================================

SELECT OrderID,
       Product,
       TotalPrice
FROM orders
ORDER BY TotalPrice DESC
LIMIT 10;

-- =====================================================
-- Query 14: Count Orders by Product
-- Purpose: Find how many orders each product received.
-- =====================================================

SELECT Product,
       COUNT(*) AS Total_Orders
FROM orders
GROUP BY Product;

-- =====================================================
-- Query 15: Average Order Value by Product
-- Purpose: Calculate the average order value for each product.
-- =====================================================

SELECT Product,
       AVG(TotalPrice) AS Average_Order_Value
FROM orders
GROUP BY Product;

-- =====================================================
-- Query 16: Total Quantity Sold by Product
-- Purpose: Find the total units sold for each product.
-- =====================================================

SELECT Product,
       SUM(Quantity) AS Total_Quantity
FROM orders
GROUP BY Product
ORDER BY Total_Quantity DESC;

-- =====================================================
-- Query 17: Orders with Coupon Codes
-- Purpose: Display all orders where a coupon was applied.
-- =====================================================

SELECT *
FROM orders
WHERE CouponCode IS NOT NULL;

-- =====================================================
-- Query 18: Orders by Payment Method
-- Purpose: Count the number of orders for each payment method.
-- =====================================================

SELECT PaymentMethod,
       COUNT(*) AS Number_of_Orders
FROM orders
GROUP BY PaymentMethod;

-- =====================================================
-- Query 19: Orders by Status
-- Purpose: Count orders based on their current status.
-- =====================================================

SELECT OrderStatus,
       COUNT(*) AS Total_Orders
FROM orders
GROUP BY OrderStatus;

-- =====================================================
-- Query 20: Product with Highest Revenue
-- Purpose: Find the top-performing product by revenue.
-- =====================================================

SELECT Product,
       SUM(TotalPrice) AS Revenue
FROM orders
GROUP BY Product
ORDER BY Revenue DESC
LIMIT 1;

-- =====================================================
-- Query 21: Monthly Revenue Analysis
-- Purpose: Calculate total revenue generated in each month.
-- =====================================================

SELECT MONTH(Date) AS Month,
       SUM(TotalPrice) AS Revenue
FROM orders
GROUP BY MONTH(Date)
ORDER BY Month;